// sidebar
export const TOGGLE_TWEET_BAR = 'TOGGLE_TWEET_BAR'
export const TOGGLE_SEARCH_BAR = 'TOGGLE_SEARCH_BAR'
export const TOGGLE_NOTIFICATION_BAR = 'TOGGLE_NOTIFICATION_BAR'
export const TOGGLE_LIST_BAR = 'TOGGLE_LIST_BAR'
export const TOGGLE_SETTING_BAR = 'TOGGLE_SETTING_BAR'
export const CLOSE_ALL_BAR = 'CLOSE_ALL_BAR'
export const UPDATE_FORM_TEXT = 'UPDATE_FORM_TEXT'
export const CLEAR_FORM_TEXT = 'CLEAR_FORM_TEXT'

// user
export const INIT_USER = 'INIT_USER'
export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
export const TOGGLE_PROFILE = 'TOGGLE_PROFILE'
export const CLOSE_PROFILE = 'CLOSE_PROFILE'

// lists
export const SET_LISTS = 'SET_LISTS'

// notification
export const SET_FAVORITE_FOR_NOTIFICATION = 'SET_FAVORITE_FOR_NOTIFICATION'
export const SET_FOLLOW_FOR_NOTIFICATION = 'SET_FOLLOW_FOR_NOTIFICATION'
export const SET_MENTION_FOR_NOTIFICATION = 'SET_MENTION_FOR_NOTIFICATION'
export const SET_RT_FOR_NOTIFICATION = 'SET_RT_FOR_NOTIFICATION'
export const CLEAR_NOTIFICATION_COUNT = 'CLEAR_NOTIFICATION_COUNT'

// tweets
export const UPDATE_TWEET_NAME = 'UPDATE_TWEET_NAME'
export const ADD_TWEETS = 'ADD_TWEETS'
export const CLEAR_TWEETS = 'CLEAR_TWEETS'
export const INCREASE_RT_COUNT = 'INCREASE_RT_COUNT'
export const INCREASE_RT_COUNT_OF_RT = 'INCREASE_RT_COUNT_OF_RT'
export const DECREASE_RT_COUNT = 'DECREASE_RT_COUNT'
export const DECREASE_RT_COUNT_OF_RT = 'DECREASE_RT_COUNT_OF_RT'
export const INCREASE_FAV_COUNT = 'INCREASE_FAV_COUNT'
export const INCREASE_FAV_COUNT_OF_RT = 'INCREASE_FAV_COUNT_OF_RT'
export const DECREASE_FAV_COUNT = 'DECREASE_FAV_COUNT'
export const DECREASE_FAV_COUNT_OF_RT = 'DECREASE_FAV_COUNT_OF_RT'
